# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/tama/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/tama


PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    vulkan.qcom \
    libC2D2 \
    libCB \
    libOpenCL \
    libRSDriver_adreno \
    libadreno_utils \
    libbccQTI \
    libc2d30_bltlib \
    libgsl \
    libllvm-glnext \
    libllvm-qcom \
    librs_adreno \
    librs_adreno_sha1 \
    lib-imsvtextutils \
    lib-imsvtutils \
    libadsprpc_system \
    libcdsprpc_system \
    libdiag_system \
    libimscamera_jni \
    libimsmedia_jni \
    libmdsprpc_system \
    libsdsprpc_system \
    CneApp \
    QtiTelephonyService \
    datastatusnotification \
    embms \
    uceShimService \
    uimgbaservice \
    uimlpaservice \
    uimremoteclient \
    uimremoteserver \
    QtiTelephonyServicelibrary \
    com.qti.dpmframework \
    com.qualcomm.qti.imscmservice-V2.0-java \
    com.qualcomm.qti.imscmservice-V2.1-java \
    com.qualcomm.qti.imscmservice-V2.2-java \
    dpmapi \
    embmslibrary \
    qcrilhook \
    qti-telephony-hidl-wrapper \
    qti-telephony-utils \
    uimgbalibrary \
    uimgbamanagerlibrary \
    uimlpalibrary \
    uimremoteserverlibrary \
    uimservicelibrary \
    vendor.qti.data.factory-V1.0-java \
    vendor.qti.data.factory-V2.0-java \
    vendor.qti.hardware.data.connection-V1.0-java \
    vendor.qti.hardware.data.connection-V1.1-java \
    vendor.qti.hardware.data.dynamicdds-V1.0-java \
    vendor.qti.ims.callinfo-V1.0-java \
    vendor.qti.ims.rcsconfig-V1.0-java \
    cnss-daemon
